// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArfPzpX5pW3rl-aN-9lN0HJ3DWLhPKlck',
    appId: '1:1000888321888:web:c71252e97abc053db50005',
    messagingSenderId: '1000888321888',
    projectId: 'femnet-3e68f',
    authDomain: 'femnet-3e68f.firebaseapp.com',
    storageBucket: 'femnet-3e68f.appspot.com',
    measurementId: 'G-QSL8FE23JG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOQxSS_07FLSUHnI7Fb5_c58gWS0yXLts',
    appId: '1:1000888321888:android:0cde0586d59458ceb50005',
    messagingSenderId: '1000888321888',
    projectId: 'femnet-3e68f',
    storageBucket: 'femnet-3e68f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqGJnYx-Josaf8h3UJO60nDD6R88AWvLg',
    appId: '1:1000888321888:ios:038c126aa95c83f2b50005',
    messagingSenderId: '1000888321888',
    projectId: 'femnet-3e68f',
    storageBucket: 'femnet-3e68f.appspot.com',
    iosClientId: '1000888321888-4u59q0u8kc8v0ctcha1ec1s3gjc12olo.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontendsrc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqGJnYx-Josaf8h3UJO60nDD6R88AWvLg',
    appId: '1:1000888321888:ios:d0406fdf18a66486b50005',
    messagingSenderId: '1000888321888',
    projectId: 'femnet-3e68f',
    storageBucket: 'femnet-3e68f.appspot.com',
    iosClientId: '1000888321888-auhv42k90llhn0u13rlgmg20npq2p9qn.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontendsrc.RunnerTests',
  );
}
