// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA59SKPkRpEvXcU8_unnpDBMDGEajC3rOc',
    appId: '1:672278888512:web:68d5937c5c9c8eaf0c5fa5',
    messagingSenderId: '672278888512',
    projectId: 'femcycle-c9ef5',
    authDomain: 'femcycle-c9ef5.firebaseapp.com',
    storageBucket: 'femcycle-c9ef5.appspot.com',
    measurementId: 'G-BEGGJWBXEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-9XiPjglaiA_Alne81Qo2nXurPfu3VM0',
    appId: '1:672278888512:android:fd7a40bff869952d0c5fa5',
    messagingSenderId: '672278888512',
    projectId: 'femcycle-c9ef5',
    storageBucket: 'femcycle-c9ef5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC96_LPKAdoPHj59hmre1nYQiPhI7Oil1Y',
    appId: '1:672278888512:ios:cf7588bf58fe75660c5fa5',
    messagingSenderId: '672278888512',
    projectId: 'femcycle-c9ef5',
    storageBucket: 'femcycle-c9ef5.appspot.com',
    iosClientId: '672278888512-b83vioe2ig5k4h9ljssiu8aot2kcidap.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC96_LPKAdoPHj59hmre1nYQiPhI7Oil1Y',
    appId: '1:672278888512:ios:cf7588bf58fe75660c5fa5',
    messagingSenderId: '672278888512',
    projectId: 'femcycle-c9ef5',
    storageBucket: 'femcycle-c9ef5.appspot.com',
    iosClientId: '672278888512-b83vioe2ig5k4h9ljssiu8aot2kcidap.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );
}
